# Generated by Django 3.0.5 on 2020-04-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('Episode', models.TextField()),
                ('Airdate', models.TextField()),
                ('Round', models.TextField()),
                ('Category', models.TextField()),
                ('Worth', models.TextField()),
                ('Clue', models.TextField()),
                ('Answer', models.TextField()),
            ],
        ),
    ]
