# Generated by Django 3.0.5 on 2020-04-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200429_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clues',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
