# Generated by Django 3.0.5 on 2020-04-29 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_questions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clues',
        ),
    ]
