# Generated by Django 3.0.5 on 2020-04-29 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_clues'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clues',
        ),
        migrations.DeleteModel(
            name='questions',
        ),
    ]
