# Generated by Django 3.0.5 on 2020-04-29 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_clues'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clues',
            old_name='Airdate',
            new_name='airdate',
        ),
        migrations.RenameField(
            model_name='clues',
            old_name='Answer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='clues',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='clues',
            old_name='Clue',
            new_name='clue',
        ),
        migrations.RenameField(
            model_name='clues',
            old_name='Episode',
            new_name='episode',
        ),
        migrations.RenameField(
            model_name='clues',
            old_name='Round',
            new_name='round',
        ),
        migrations.RenameField(
            model_name='clues',
            old_name='Worth',
            new_name='worth',
        ),
    ]
